/** Uzbek UI strings for customer-facing app */
export const uz = {
  cityName: 'CHUST',
  citySubtitle: "Shahar bo'ylab yetkazish",
  searchPlaceholder: "Restoranlar, taomlar va mahsulotlarni qidiring...",
  searchAria: 'Qidiruv',
  filterAria: 'Filtr',
  restaurants: 'Restoranlar',
  allRestaurants: 'Barcha restoranlar',
  dishCategories: 'Taom kategoriyalari',
  homeSecondaryBanners: 'Bosh sahifa bannerlari',
  seeAll: 'Barchasi',
  retry: 'Qayta urinish',
  restaurantsLoadError: 'Restoranlar yuklanmadi',
  productsLoadError: 'Mahsulotlar yuklanmadi',
  checkConnection: "Internet aloqasini tekshiring",
  restaurantsComingSoon: 'Tez orada restoranlar',
  restaurantsEmptyHint:
    "Hozircha ro'yxat bo'sh. Admin panelda restoranlarni faollashtiring va tasdiqlang.",
  freeDeliveryFrom: (amount: string) => `${amount}dan bepul`,
  deliveryTime: (range: string) => range,
  min: 'daq',
  favoritesTitle: 'Sevimlilar',
  favoritesEmpty: "Hali sevimlilar yo'q",
  favoritesEmptyHint:
    "Restoranlarni yurakcha bilan saqlang — tez orada bu yerda ko'rinadi.",
  cartTitle: 'Savat',
  cartEmpty: "Savat bo'sh",
  browseRestaurants: "Restoranlarni ko'rish",
  remove: "O'chirish",
  subtotal: 'Jami',
  clear: 'Tozalash',
  checkout: 'Buyurtma berish',
  checkoutStepDetails: 'Ma\'lumotlar',
  checkoutStepDelivery: 'Yetkazish',
  checkoutTitle: 'Buyurtmani rasmiylashtirish',
  checkoutHeading: 'Buyurtmangiz',
  checkoutItemCount: (count: number) => `${count} ta mahsulot`,
  checkoutPromoLabel: '🎁 Promo kod',
  checkoutGrandTotal: 'JAMI',
  checkoutPlaceOrderWithTotal: (total: string) => `🛵 ${total}ga buyurtma berish`,
  checkoutEnterPhone: 'Telefon raqamini kiriting',
  checkoutPhoneEntered: 'Raqam kiritildi',
  checkoutPlaceOrder: 'Buyurtmani rasmiylashtirish',
  checkoutEta: (min: number) => `Taxminan ${min} daqiqa`,
  noAccountRequired: 'Ro\'yxatdan o\'tish shart emas',
  back: 'Orqaga',
  promoCode: 'Promo kod',
  apply: 'Qo\'llash',
  promoDiscount: (amount: string) => `Chegirma: ${amount}`,
  invalidPromo: 'Promo kod noto\'g\'ri',
  phone: 'Telefon',
  phoneHint: '90 123 45 67',
  deliveryAddress: 'Yetkazish manzili',
  deliveryAddressOptional: 'Manzil (ixtiyoriy — yetkazishni aniqlashtirish uchun)',
  sendLocation: 'Joylashuvni yuborish',
  calculateDeliveryPrice: 'Yetkazish narxini hisoblash',
  recalculateDeliveryPrice: 'Yetkazish narxini qayta hisoblash',
  deliveryPriceHint:
    'Yetkazish narxini bilish uchun tugmani bosing. Manzil ixtiyoriy.',
  deliveryCalculating: 'Yetkazish narxi hisoblanmoqda...',
  deliveryPriceCalculated: 'Yetkazish narxi hisoblandi',
  deliveryPriceRequired:
    'Buyurtma berishdan oldin yetkazish narxini hisoblang (joylashuvni yuboring).',
  locationSent: 'Joylashuv qabul qilindi — narx hisoblanmoqda',
  detectingLocation: 'Aniqlanmoqda...',
  deliveryAddressRequired: 'Yetkazish manzilini kiriting.',
  locationRequired: 'Yetkazish uchun «Joylashuvni yuborish» tugmasini bosing.',
  locationSendFailed: 'Joylashuvni yuborib bo\'lmadi. Ruxsat bering yoki qayta urinib ko\'ring.',
  coordsLabel: 'Koordinatalar',
  coordsMissing: 'Koordinatalar kiritilmagan',
  openInMaps: 'Xaritada ochish',
  commentOptional: 'Izoh (ixtiyoriy)',
  placingOrder: 'Buyurtma yuborilmoqda...',
  placeOrder: 'Buyurtmani tasdiqlash',
  orderFailed: 'Buyurtma amalga oshmadi',
  deliveryFee: 'yetkazish',
  deliveryLabel: 'Yetkazish',
  productsSubtotal: 'Mahsulotlar',
  orderTotal: 'Jami',
  promoApplied: 'Chegirma',
  locationRequiredShort: 'Joylashuv kerak',
  distanceKm: (km: number) => `Masofa: ${km} km`,
  ordersTitle: 'Buyurtmalarim',
  ordersSubtitle: 'Ushbu qurilmadan berilgan buyurtmalar',
  noOrders: "Hali buyurtmalar yo'q",
  noOrdersHint: "Restorandan buyurtma bering — bu yerda ko'rinadi",
  track: 'Kuzatish',
  order: 'Buyurtma',
  loading: 'Yuklanmoqda...',
  restaurantNotFound: 'Restoran topilmadi',
  open: 'Ochiq',
  closed: 'Yopiq',
  closesAt: (time: string) => `${time} da yopiladi`,
  openNowHint: 'Hozir buyurtma bera olasiz',
  closingSoonTitle: 'Tez orada yopiladi',
  closedHint: 'Menyuni ko\'rishingiz mumkin, buyurtma berib bo\'lmaydi.',
  restaurantClosed: 'Restoran hozir yopiq. Menyuni ko\'rishingiz mumkin, buyurtma berib bo\'lmaydi.',
  menuEmpty: "Menyu hali yo'q",
  menuEmptyHint: 'Tez orada taomlar shu yerda paydo bo\'ladi.',
  backToSite: 'Saytga qaytish',
  addToCart: "Qo'shish",
  cartFab: (count: number) => `Savat (${count})`,
  profile: 'Profil',
  profileAccount: 'Hisob',
  profileGuestName: 'Mehmon',
  profileLoginSubtitle: 'akkauntga kiring',
  profileRegisterSubtitle: "yangi hisob oching",
  profileTelegramSubtitle: 'tez kirish',
  profilePromotionsSubtitle: 'maxsus takliflar',
  profileNotificationsSubtitle: 'yangi xabarlar',
  profileHelpSubtitle: 'savollar va yordam',
  profileTermsSubtitle: 'qoidalar va maxfiylik',
  profileLanguageSubtitle: "o'zbek / русский",
  profileHint: 'Tez buyurtma va tarix uchun telefon raqamingizni saqlang',
  guestGreeting: 'Salom!',
  guestUserTitle: 'Mehmon foydalanuvchi',
  guestUserDescription: "FoodApp'dan ro'yxatdan o'tmasdan ham foydalanishingiz mumkin.",
  guestUserBenefits:
    'Hisob ochsangiz buyurtmalar tarixi, manzillar va sevimlilar saqlanadi',
  guestAccountBenefitsLabel: 'Hisob ochsangiz qulayliklar',
  guestPromoBanner:
    "Ro'yxatdan o'ting va maxsus chegirmalar hamda aksiyalardan foydalaning",
  guestFeatureBonusesTitle: 'Bonuslar',
  guestFeaturesSectionTitle: 'Hisob ochsangiz',
  quickActions: 'Tezkor kirish',
  loginRequiredForFeature: "Bu bo'limdan foydalanish uchun tizimga kiring",
  notNow: 'Hozircha kerak emas',
  languageSection: 'Til',
  changeLanguage: "Tilni o'zgartirish",
  authSheetLoginSubtitle:
    'Buyurtmalar tarixi, saqlangan manzillar va tezkor buyurtmalar uchun tizimga kiring',
  authSheetRegisterSubtitle: "Bir necha qadamda hisob oching — tez va oson",
  backToTelegram: 'Telegram orqali kirishga qaytish',
  registerStepPhone: 'Telefon raqamingiz',
  registerStepPhoneHint: 'SMS orqali tasdiqlash kodi yuboramiz',
  registerStepOtp: 'SMS kodni kiriting',
  registerStepOtpHint:
    'Kod tez orada avtomatik tasdiqlanadi. Hozircha test uchun kodni kiriting va davom eting.',
  registerStepName: 'Ismingiz',
  registerStepNameHint: 'Kuryer va restoran sizni shu ism bilan chaqiradi',
  phoneInvalid: 'Telefon raqam noto\'g\'ri',
  otpInvalid: 'Kamida 4 raqamli kod kiriting',
  nameRequired: 'Ism kamida 2 harfdan iborat bo\'lishi kerak',
  otpResendSoon: 'SMS xizmati tez orada ulanadi',
  resendCode: 'Kodni qayta yuborish',
  continue: 'Davom etish',
  guestFeatureFavoritesTitle: 'Sevimlilar',
  guestFeatureFavoritesDesc: "Yoqtirgan restoran va mahsulotlarni saqlang",
  guestFeatureOrdersTitle: 'Buyurtmalar tarixi',
  guestFeatureOrdersDesc: "Oldingi buyurtmalaringizni ko'ring",
  guestFeatureAddressesTitle: 'Manzillar',
  guestFeatureAddressesDesc: 'Yetkazib berish manzillarini saqlang',
  guestFeatureFastOrderTitle: 'Tez buyurtma',
  guestFeatureFastOrderDesc: 'Keyingi buyurtmalarni tezroq bering',
  helpfulSections: "Ma'lumot va yordam",
  profileHelp: 'Yordam',
  profileHelpHint: 'FAQ va qo\'llab-quvvatlash',
  profilePartnership: 'Hamkorlik',
  profilePartnershipHint: 'Biznes takliflari va hamkorlik',
  contactViaTelegram: "Telegram orqali bog'laning",
  contactViaPhone: "Telefon orqali bog'laning",
  openTelegram: 'Telegramga yozish',
  contactNotConfigured: "Hozircha bog'lanish ma'lumotlari sozlanmagan.",
  profileSocialTitle: "Bizni ijtimoiy tarmoqlarda kuzatib boring",
  profileSocialFollow: "obuna bo'ling",
  profileSocialLinkMissing: 'Havola hali sozlanmagan. Admin panelda saqlang.',
  termsOfUse: 'Foydalanish shartlari',
  privacyPolicy: 'Maxfiylik siyosati',
  close: 'Yopish',
  customer: 'Mijoz',
  staff: 'Xodim',
  signIn: 'Kirish',
  register: "Ro'yxatdan o'tish",
  signOut: 'Chiqish',
  fullName: "To'liq ism",
  emailOptional: 'Email (ixtiyoriy)',
  referralOptional: "Do'stingizning referral kodi (ixtiyoriy)",
  creatingAccount: 'Yaratilmoqda...',
  createAccount: "Hisob yaratish",
  signingIn: 'Kirish...',
  welcome: (name: string) => `Xush kelibsiz, ${name}!`,
  welcomeRegistered: "Hisobingiz tayyor.",
  referralCode: (code: string) => `Referral kodingiz: ${code}`,
  loggedOut: 'Tizimdan chiqdingiz.',
  loyalty: (level: string, points: number) => `Sadoqat · ${level} · ${points} ball`,
  yourReferral: 'Referral kodingiz',
  platformAdmin: 'Platforma admini?',
  openStaffLogin: 'Xodimlar kirishini ochish',
  navHome: 'Bosh sahifa',
  navRestaurants: 'Restoranlar',
  navProducts: 'Mahsulotlar',
  navShops: "Do'konlar",
  shopsTitle: "Do'konlar",
  shopsSubtitle: "Shahardagi barcha do'konlar va xizmatlar",
  shopsSearchPlaceholder: "Do'kon yoki mahsulot qidiring...",
  shopsLoadError: "Do'konlar yuklanmadi",
  shopsEmpty: "Do'konlar topilmadi",
  shopsEmptyHint: "Boshqa kategoriya yoki qidiruv so'zini sinab ko'ring",
  popularBusinesses: 'Mashhur do\'konlar',
  allBusinesses: 'Barcha do\'konlar',
  categories: 'Kategoriyalar',
  filterPopular: 'Mashhur',
  filterNearest: 'Yaqin',
  filterRating: 'Reyting',
  filterFastest: 'Tez yetkazish',
  navCart: 'Savat',
  navProfile: 'Profil',
  favoritesAria: 'Sevimlilar',
  notificationsAria: 'Bildirishnomalar',
  notificationsTitle: 'Bildirishnomalar',
  notificationsEmptyHint: "Hozircha yangi bildirishnomalar yo'q.",
  notificationsLoginHint: 'Bildirishnomalarni ko‘rish uchun tizimga kiring.',
  notificationsMarkAllRead: 'Hammasini o‘qilgan',
  notificationsRefreshHint: 'Yangilanishlar avtomatik yuklanadi.',
  notificationsUnreadBadge: (n: number) => (n > 99 ? '99+' : String(n)),
  pwaInstallAria: 'Ilovani o‘rnatish',
  pwaIosInstallTitle: 'iPhone\'ga o‘rnatish',
  pwaIosInstallSubtitle: 'FoodApp\'ni bosh ekranga qo‘shing — tezroq ochiladi',
  pwaIosInstallStep1: 'Safari brauzerida pastdagi «Ulashish» tugmasini bosing',
  pwaIosInstallStep2: '«Bosh ekranga qo‘shish» bandini tanlang',
  pwaIosInstallStep3: '«Qo‘shish» tugmasini bosing',
  telegramSocialAria: 'Telegramga o‘tish',
  promotionsTitle: 'Aksiyalar',
  promotionsEmptyHint: "Maxsus takliflar tez orada shu yerda ko'rinadi.",
  productsTitle: 'Mahsulotlar',
  productsEmptyHint: "Tez orada supermarket va do'kon mahsulotlari bu yerda paydo bo'ladi.",
  appTitle: 'FoodApp',
  appSubtitle: 'Yetkazib berish',
  geolocationUnsupported: 'Geolokatsiya qo\'llab-quvvatlanmaydi',
  geolocationFailed: 'Joylashuv aniqlanmadi',
  promoValidateFailed: 'Promo kodni tekshirish mumkin emas edi',
  slide: (n: number) => `Slayd ${n}`,
  registrationFailed: "Ro'yxatdan o'tish amalga oshmadi",
  loginFailed: 'Kirish amalga oshmadi',
  loginSubtitle: 'Telegram orqali tez kirish yoki telefon raqamidan foydalaning',
  authBenefitsDescription:
    "Buyurtmalar tarixi, saqlangan manzillar va tezkor buyurtma uchun tizimga kiring",
  loginWithTelegram: 'Telegram orqali kirish',
  continueWithGoogle: 'Google orqali davom etish',
  googleNotConfigured:
    'Google kirish sozlanmagan (NEXT_PUBLIC_FIREBASE_API_KEY, AUTH_DOMAIN, PROJECT_ID)',
  googleSignInCancelled: 'Google kirish bekor qilindi',
  googleSignInFailed: 'Google orqali kirish amalga oshmadi',
  loginWithPhone: 'Telefon raqam orqali kirish',
  loginWithPhonePassword: 'Telefon va parol orqali kirish',
  password: 'Parol',
  showPassword: "Parolni ko'rsatish",
  hidePassword: "Parolni yashirish",
  confirmPassword: 'Parolni tasdiqlang',
  passwordMismatch: 'Parollar mos kelmaydi',
  passwordTooShort: 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak',
  alreadyHaveAccount: 'Hisobingiz bormi?',
  backToProfile: 'Profilga qaytish',
  passwordOptionalHint: "Parol o'rnatilmagan bo'lsa, bo'sh qoldiring",
  forgotPassword: 'Parolni unutdingizmi?',
  forgotPasswordSoon: "Parolni tiklash tez orada qo'shiladi",
  staffLoginForEmployees: 'Xodimlar uchun kirish',
  backToCustomerLogin: 'Mijoz kirishiga qaytish',
  staffLoginIdPlaceholder: 'Email yoki telefon',
  staffSignIn: 'Xodim sifatida kirish',
  telegramCardHint: 'Bir teginish orqali xavfsiz va tez autentifikatsiya',
  telegramNotConfigured: 'Telegram bot sozlanmagan (NEXT_PUBLIC_TELEGRAM_BOT_USERNAME)',
  telegramLoginHint: 'Telegram hisobingiz orqali xavfsiz kirish',
  noAccount: "Hisobingiz yo'qmi?",
  or: 'yoki',
  completeProfileTitle: 'Profilni yakunlang',
  completeProfileHint:
    'Buyurtma berish uchun telefon raqamingiz kerak. Manzil ixtiyoriy — keyinroq ham kiritishingiz mumkin.',
  optional: 'ixtiyoriy',
  saving: 'Saqlanmoqda...',
  saveAndContinue: 'Davom etish',
  addPhone: "Telefon qo'shish",
  telegramProfile: 'Telegram',
  telegramUsernameLabel: 'Username',
  telegramIdLabel: 'Telegram ID',
  lastTelegramLogin: 'Oxirgi kirish',
  goToLogin: 'Kirish sahifasiga',
  phoneRequiredForOrders: 'Buyurtma uchun telefon raqam kerak',
  orderNotFound: 'Buyurtma topilmadi',
  orderNumber: (n: string) => `Buyurtma #${n}`,
  liveUpdates: 'Jonli yangilanishlar yoqilgan',
  total: 'Jami',
  noResults: 'Natija topilmadi',
  tryOtherSearch: "Boshqa so'z bilan qidiring",
  staffAccount: 'Xodim hisobi',
  staffSignOut: 'Xodim hisobidan chiqish',
  staffLoginTitle: 'Xodim va Super Admin',
  staffLoginHint: 'Ish email va parol bilan kiring.',
  staffFullLogin: "To'liq ekranli kirish",
  staffPanels: {
    SUPER_ADMIN: 'Super Admin paneli',
    MANAGER: 'Menejer paneli',
    BUSINESS: 'Biznes paneli',
    RESTAURANT_OWNER: 'Biznes paneli',
    RESTAURANT_STAFF: 'Biznes paneli',
    COURIER: 'Kuryer paneli',
  } as Record<string, string>,
  bookingBadge: 'Stol bron',
  bookingTitle: 'Stol va zal bron qiling',
  bookingSubtitle:
    'Restoranlar va zallar — bayramlar, oilaviy uchrashuvlar va maxsus kechalar uchun.',
  bookingFeatureTables: 'Stollar',
  bookingFeatureTablesHint: 'Romantik kechalar va uchrashuvlar',
  bookingFeatureHalls: 'Bayram zallari',
  bookingFeatureHallsHint: "Tug'ilgan kun, to'y va korporativ",
  bookingVenuesTitle: 'Joylar',
  bookingEmpty: "Hozircha joylar qo'shilmagan",
  bookingViewVenue: "Batafsil ko'rish",
  bookingCallToReserve: "Bron uchun qo'ng'iroq",
  bookingNoPhone: "Telefon raqami qo'shilmagan",
  bookingVenueNotFound: 'Joy topilmadi',
  bookingTypeTable: 'Stol',
  bookingTypeHall: 'Zal',
  bookingTypeBoth: 'Stol va zal',
  orderStatus: {
    PENDING: 'Restoran kutmoqda',
    ACCEPTED: 'Buyurtma qabul qilindi',
    PREPARING: 'Taom tayyorlanmoqda',
    COURIER_ASSIGNED: 'Kuryer biriktirildi',
    ARRIVED_AT_RESTAURANT: 'Restoranga yetib bordi',
    PICKED_UP: 'Olib ketildi',
    DELIVERING: "Yo'lda",
    DELIVERED: 'Yetkazildi',
    CANCELLED: 'Bekor qilindi',
  } as Record<string, string>,
} as const;
