/** Uzbek UI strings for customer-facing app */
export const uz = {
  cityName: 'CHUST',
  citySubtitle: "Shahar bo'ylab yetkazish",
  searchPlaceholder: "Restoranlar, taomlar va mahsulotlarni qidiring...",
  searchAria: 'Qidiruv',
  filterAria: 'Filtr',
  restaurants: 'Restoranlar',
  seeAll: 'Barchasi',
  retry: 'Qayta urinish',
  restaurantsLoadError: 'Restoranlar yuklanmadi',
  checkConnection: "Internet aloqasini tekshiring",
  restaurantsComingSoon: 'Tez orada restoranlar',
  restaurantsEmptyHint:
    "Hozircha ro'yxat bo'sh. Admin panelda restoranlarni faollashtiring va tasdiqlang.",
  freeDeliveryFrom: (amount: string) => `${amount}dan bepul`,
  deliveryTime: (range: string) => range,
  min: 'daq',
  favoritesTitle: 'Sevimlilar',
  favoritesEmpty: "Hali sevimlilar yo'q",
  favoritesEmptyHint:
    "Restoranlarni yurakcha bilan saqlang — tez orada bu yerda ko'rinadi.",
  cartTitle: 'Savat',
  cartEmpty: "Savat bo'sh",
  browseRestaurants: "Restoranlarni ko'rish",
  remove: "O'chirish",
  subtotal: 'Jami',
  clear: 'Tozalash',
  checkout: 'Buyurtma berish',
  checkoutTitle: 'Buyurtmani rasmiylashtirish',
  noAccountRequired: 'Ro\'yxatdan o\'tish shart emas',
  back: 'Orqaga',
  promoCode: 'Promo kod',
  apply: 'Qo\'llash',
  promoDiscount: (amount: string) => `Chegirma: ${amount}`,
  invalidPromo: 'Promo kod noto\'g\'ri',
  phone: 'Telefon (+998901234567)',
  deliveryAddress: 'Yetkazish manzili',
  sendLocation: 'Joylashuvni yuborish',
  locationSent: 'Joylashuv qabul qilindi',
  detectingLocation: 'Aniqlanmoqda...',
  deliveryAddressRequired: 'Yetkazish manzilini kiriting.',
  locationRequired: 'Yetkazish uchun «Joylashuvni yuborish» tugmasini bosing.',
  locationSendFailed: 'Joylashuvni yuborib bo\'lmadi. Ruxsat bering yoki qayta urinib ko\'ring.',
  coordsLabel: 'Koordinatalar',
  coordsMissing: 'Koordinatalar kiritilmagan',
  openInMaps: 'Xaritada ochish',
  commentOptional: 'Izoh (ixtiyoriy)',
  placingOrder: 'Buyurtma yuborilmoqda...',
  placeOrder: 'Buyurtmani tasdiqlash',
  orderFailed: 'Buyurtma amalga oshmadi',
  deliveryFee: 'yetkazish',
  ordersTitle: 'Buyurtmalarim',
  ordersSubtitle: 'Ushbu qurilmadan berilgan buyurtmalar',
  noOrders: "Hali buyurtmalar yo'q",
  noOrdersHint: "Restorandan buyurtma bering — bu yerda ko'rinadi",
  track: 'Kuzatish',
  order: 'Buyurtma',
  loading: 'Yuklanmoqda...',
  restaurantNotFound: 'Restoran topilmadi',
  restaurantClosed: 'Restoran hozir yopiq. Menyuni ko\'rishingiz mumkin, buyurtma berib bo\'lmaydi.',
  menuEmpty: "Menyu hali yo'q",
  menuEmptyHint: 'Tez orada taomlar shu yerda paydo bo\'ladi.',
  backToSite: 'Saytga qaytish',
  addToCart: "Qo'shish",
  cartFab: (count: number) => `Savat (${count})`,
  profile: 'Profil',
  profileHint: 'Tez buyurtma va tarix uchun telefon raqamingizni saqlang',
  guestGreeting: 'Salom!',
  guestUserTitle: 'Mehmon foydalanuvchi',
  guestUserDescription: "FoodApp'dan ro'yxatdan o'tmasdan ham foydalanishingiz mumkin.",
  guestUserBenefits:
    'Hisob ochsangiz buyurtmalar tarixi, manzillar va sevimlilar saqlanadi',
  guestAccountBenefitsLabel: 'Hisob ochsangiz qulayliklar',
  guestPromoBanner:
    "Ro'yxatdan o'ting va maxsus chegirmalar hamda aksiyalardan foydalaning",
  guestFeatureBonusesTitle: 'Bonuslar',
  guestFeaturesSectionTitle: 'Hisob ochsangiz',
  quickActions: 'Tezkor kirish',
  loginRequiredForFeature: "Bu bo'limdan foydalanish uchun tizimga kiring",
  notNow: 'Hozircha kerak emas',
  languageSection: 'Til',
  changeLanguage: "Tilni o'zgartirish",
  authSheetLoginSubtitle:
    'Buyurtmalar tarixi, saqlangan manzillar va tezkor buyurtmalar uchun tizimga kiring',
  authSheetRegisterSubtitle: "Bir necha qadamda hisob oching — tez va oson",
  backToTelegram: 'Telegram orqali kirishga qaytish',
  registerStepPhone: 'Telefon raqamingiz',
  registerStepPhoneHint: 'SMS orqali tasdiqlash kodi yuboramiz',
  registerStepOtp: 'SMS kodni kiriting',
  registerStepOtpHint:
    'Kod tez orada avtomatik tasdiqlanadi. Hozircha test uchun kodni kiriting va davom eting.',
  registerStepName: 'Ismingiz',
  registerStepNameHint: 'Kuryer va restoran sizni shu ism bilan chaqiradi',
  phoneInvalid: 'Telefon raqam noto\'g\'ri',
  otpInvalid: 'Kamida 4 raqamli kod kiriting',
  nameRequired: 'Ism kamida 2 harfdan iborat bo\'lishi kerak',
  otpResendSoon: 'SMS xizmati tez orada ulanadi',
  resendCode: 'Kodni qayta yuborish',
  continue: 'Davom etish',
  guestFeatureFavoritesTitle: 'Sevimlilar',
  guestFeatureFavoritesDesc: "Yoqtirgan restoran va mahsulotlarni saqlang",
  guestFeatureOrdersTitle: 'Buyurtmalar tarixi',
  guestFeatureOrdersDesc: "Oldingi buyurtmalaringizni ko'ring",
  guestFeatureAddressesTitle: 'Manzillar',
  guestFeatureAddressesDesc: 'Yetkazib berish manzillarini saqlang',
  guestFeatureFastOrderTitle: 'Tez buyurtma',
  guestFeatureFastOrderDesc: 'Keyingi buyurtmalarni tezroq bering',
  helpfulSections: "Ma'lumot va yordam",
  profileHelp: 'Yordam',
  profileHelpHint: 'FAQ va qo\'llab-quvvatlash',
  profilePartnership: 'Takliflar va hamkorlik',
  profilePartnershipHint: 'Biznes takliflari va hamkorlik',
  termsOfUse: 'Foydalanish shartlari',
  privacyPolicy: 'Maxfiylik siyosati',
  close: 'Yopish',
  customer: 'Mijoz',
  staff: 'Xodim',
  signIn: 'Kirish',
  register: "Ro'yxatdan o'tish",
  signOut: 'Chiqish',
  fullName: "To'liq ism",
  emailOptional: 'Email (ixtiyoriy)',
  referralOptional: "Do'stingizning referral kodi (ixtiyoriy)",
  creatingAccount: 'Yaratilmoqda...',
  createAccount: "Hisob yaratish",
  signingIn: 'Kirish...',
  welcome: (name: string) => `Xush kelibsiz, ${name}!`,
  welcomeRegistered: "Hisobingiz tayyor.",
  referralCode: (code: string) => `Referral kodingiz: ${code}`,
  loggedOut: 'Tizimdan chiqdingiz.',
  loyalty: (level: string, points: number) => `Sadoqat · ${level} · ${points} ball`,
  yourReferral: 'Referral kodingiz',
  platformAdmin: 'Platforma admini?',
  openStaffLogin: 'Xodimlar kirishini ochish',
  navRestaurants: 'Restoranlar',
  navProducts: 'Mahsulotlar',
  navShops: "Do'konlar",
  shopsTitle: "Do'konlar",
  shopsSubtitle: "Shahardagi barcha do'konlar va xizmatlar",
  shopsSearchPlaceholder: "Do'kon yoki mahsulot qidiring...",
  shopsLoadError: "Do'konlar yuklanmadi",
  shopsEmpty: "Do'konlar topilmadi",
  shopsEmptyHint: "Boshqa kategoriya yoki qidiruv so'zini sinab ko'ring",
  popularBusinesses: 'Mashhur do\'konlar',
  allBusinesses: 'Barcha do\'konlar',
  categories: 'Kategoriyalar',
  filterPopular: 'Mashhur',
  filterNearest: 'Yaqin',
  filterRating: 'Reyting',
  filterFastest: 'Tez yetkazish',
  navCart: 'Savat',
  navProfile: 'Profil',
  favoritesAria: 'Sevimlilar',
  notificationsAria: 'Bildirishnomalar',
  notificationsTitle: 'Bildirishnomalar',
  notificationsEmptyHint: "Hozircha yangi bildirishnomalar yo'q.",
  productsTitle: 'Mahsulotlar',
  productsEmptyHint: "Tez orada supermarket va do'kon mahsulotlari bu yerda paydo bo'ladi.",
  appTitle: 'FoodApp',
  appSubtitle: 'Yetkazib berish',
  geolocationUnsupported: 'Geolokatsiya qo\'llab-quvvatlanmaydi',
  geolocationFailed: 'Joylashuv aniqlanmadi',
  promoValidateFailed: 'Promo kodni tekshirish mumkin emas edi',
  slide: (n: number) => `Slayd ${n}`,
  registrationFailed: "Ro'yxatdan o'tish amalga oshmadi",
  loginFailed: 'Kirish amalga oshmadi',
  loginSubtitle: 'Telegram orqali tez kirish yoki telefon raqamidan foydalaning',
  authBenefitsDescription:
    "Buyurtmalar tarixi, saqlangan manzillar va tezkor buyurtma uchun tizimga kiring",
  loginWithTelegram: 'Telegram orqali kirish',
  loginWithPhone: 'Telefon raqam orqali kirish',
  loginWithPhonePassword: 'Telefon va parol orqali kirish',
  password: 'Parol',
  confirmPassword: 'Parolni tasdiqlang',
  passwordMismatch: 'Parollar mos kelmaydi',
  passwordTooShort: 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak',
  alreadyHaveAccount: 'Hisobingiz bormi?',
  backToProfile: 'Profilga qaytish',
  passwordOptionalHint: "Parol o'rnatilmagan bo'lsa, bo'sh qoldiring",
  forgotPassword: 'Parolni unutdingizmi?',
  forgotPasswordSoon: "Parolni tiklash tez orada qo'shiladi",
  staffLoginForEmployees: 'Xodimlar uchun kirish',
  backToCustomerLogin: 'Mijoz kirishiga qaytish',
  staffLoginIdPlaceholder: 'Email yoki telefon',
  staffSignIn: 'Xodim sifatida kirish',
  telegramCardHint: 'Bir teginish orqali xavfsiz va tez autentifikatsiya',
  telegramNotConfigured: 'Telegram bot sozlanmagan (NEXT_PUBLIC_TELEGRAM_BOT_USERNAME)',
  telegramLoginHint: 'Telegram hisobingiz orqali xavfsiz kirish',
  noAccount: "Hisobingiz yo'qmi?",
  or: 'yoki',
  completeProfileTitle: 'Profilni yakunlang',
  completeProfileHint:
    'Buyurtma berish uchun telefon raqamingiz kerak. Manzil ixtiyoriy — keyinroq ham kiritishingiz mumkin.',
  optional: 'ixtiyoriy',
  saving: 'Saqlanmoqda...',
  saveAndContinue: 'Davom etish',
  addPhone: "Telefon qo'shish",
  telegramProfile: 'Telegram',
  telegramUsernameLabel: 'Username',
  telegramIdLabel: 'Telegram ID',
  lastTelegramLogin: 'Oxirgi kirish',
  goToLogin: 'Kirish sahifasiga',
  phoneRequiredForOrders: 'Buyurtma uchun telefon raqam kerak',
  orderNotFound: 'Buyurtma topilmadi',
  orderNumber: (n: string) => `Buyurtma #${n}`,
  liveUpdates: 'Jonli yangilanishlar yoqilgan',
  total: 'Jami',
  noResults: 'Natija topilmadi',
  tryOtherSearch: "Boshqa so'z bilan qidiring",
  staffAccount: 'Xodim hisobi',
  staffSignOut: 'Xodim hisobidan chiqish',
  staffLoginTitle: 'Xodim va Super Admin',
  staffLoginHint: 'Ish email va parol bilan kiring.',
  staffFullLogin: "To'liq ekranli kirish",
  staffPanels: {
    SUPER_ADMIN: 'Super Admin paneli',
    MANAGER: 'Menejer paneli',
    BUSINESS: 'Biznes paneli',
    RESTAURANT_OWNER: 'Biznes paneli',
    RESTAURANT_STAFF: 'Biznes paneli',
    COURIER: 'Kuryer paneli',
  } as Record<string, string>,
  orderStatus: {
    PENDING: 'Restoran kutmoqda',
    ACCEPTED: 'Buyurtma qabul qilindi',
    PREPARING: 'Taom tayyorlanmoqda',
    COURIER_ASSIGNED: 'Kuryer biriktirildi',
    PICKED_UP: 'Olib ketildi',
    DELIVERING: "Yo'lda",
    DELIVERED: 'Yetkazildi',
    CANCELLED: 'Bekor qilindi',
  } as Record<string, string>,
} as const;
