/** Uzbek UI strings for customer-facing app */
export const uz = {
  cityName: 'TOSHKENT',
  citySubtitle: "Shahar bo'ylab yetkazish",
  searchPlaceholder: "Restoranlar, taomlar va mahsulotlarni qidiring...",
  searchAria: 'Qidiruv',
  filterAria: 'Filtr',
  restaurants: 'Restoranlar',
  seeAll: 'Barchasi',
  retry: 'Qayta urinish',
  restaurantsLoadError: 'Restoranlar yuklanmadi',
  checkConnection: "Internet aloqasini tekshiring",
  restaurantsComingSoon: 'Tez orada restoranlar',
  restaurantsEmptyHint:
    "Hozircha ro'yxat bo'sh. Admin panelda restoranlarni faollashtiring va tasdiqlang.",
  freeDeliveryFrom: (amount: string) => `${amount}dan bepul`,
  deliveryTime: (range: string) => range,
  min: 'daq',
  favoritesTitle: 'Sevimlilar',
  favoritesEmpty: "Hali sevimlilar yo'q",
  favoritesEmptyHint:
    "Restoranlarni yurakcha bilan saqlang — tez orada bu yerda ko'rinadi.",
  cartTitle: 'Savat',
  cartEmpty: "Savat bo'sh",
  browseRestaurants: "Restoranlarni ko'rish",
  remove: "O'chirish",
  subtotal: 'Jami',
  clear: 'Tozalash',
  checkout: 'Buyurtma berish',
  checkoutTitle: 'Buyurtmani rasmiylashtirish',
  noAccountRequired: 'Ro\'yxatdan o\'tish shart emas',
  back: 'Orqaga',
  promoCode: 'Promo kod',
  apply: 'Qo\'llash',
  promoDiscount: (amount: string) => `Chegirma: ${amount}`,
  invalidPromo: 'Promo kod noto\'g\'ri',
  phone: 'Telefon (+998901234567)',
  deliveryAddress: 'Yetkazish manzili',
  useGps: 'GPS joylashuvimni ishlatish',
  commentOptional: 'Izoh (ixtiyoriy)',
  placingOrder: 'Buyurtma yuborilmoqda...',
  placeOrder: 'Buyurtmani tasdiqlash',
  orderFailed: 'Buyurtma amalga oshmadi',
  deliveryFee: 'yetkazish',
  ordersTitle: 'Buyurtmalarim',
  ordersSubtitle: 'Ushbu qurilmadan berilgan buyurtmalar',
  noOrders: "Hali buyurtmalar yo'q",
  noOrdersHint: "Restorandan buyurtma bering — bu yerda ko'rinadi",
  track: 'Kuzatish',
  order: 'Buyurtma',
  loading: 'Yuklanmoqda...',
  restaurantNotFound: 'Restoran topilmadi',
  restaurantClosed: 'Restoran hozir yopiq. Menyuni ko\'rishingiz mumkin, buyurtma berib bo\'lmaydi.',
  addToCart: "Qo'shish",
  cartFab: (count: number) => `Savat (${count})`,
  profile: 'Profil',
  profileHint: 'Tez buyurtma va tarix uchun telefon raqamingizni saqlang',
  customer: 'Mijoz',
  staff: 'Xodim',
  signIn: 'Kirish',
  register: "Ro'yxatdan o'tish",
  signOut: 'Chiqish',
  fullName: "To'liq ism",
  emailOptional: 'Email (ixtiyoriy)',
  referralOptional: "Do'stingizning referral kodi (ixtiyoriy)",
  creatingAccount: 'Yaratilmoqda...',
  createAccount: "Hisob yaratish",
  signingIn: 'Kirish...',
  welcome: (name: string) => `Xush kelibsiz, ${name}!`,
  welcomeRegistered: "Hisobingiz tayyor.",
  referralCode: (code: string) => `Referral kodingiz: ${code}`,
  loggedOut: 'Tizimdan chiqdingiz.',
  loyalty: (level: string, points: number) => `Sadoqat · ${level} · ${points} ball`,
  yourReferral: 'Referral kodingiz',
  platformAdmin: 'Platforma admini?',
  openStaffLogin: 'Xodimlar kirishini ochish',
  navHome: 'Bosh sahifa',
  navOrders: 'Buyurtmalarim',
  navFavorites: 'Sevimlilar',
  navProfile: 'Profil',
  appTitle: 'FoodApp',
  appSubtitle: 'Yetkazib berish',
  geolocationUnsupported: 'Geolokatsiya qo\'llab-quvvatlanmaydi',
  geolocationFailed: 'Joylashuv aniqlanmadi',
  promoValidateFailed: 'Promo kodni tekshirish mumkin emas edi',
  slide: (n: number) => `Slayd ${n}`,
  registrationFailed: "Ro'yxatdan o'tish amalga oshmadi",
  loginFailed: 'Kirish amalga oshmadi',
  orderNotFound: 'Buyurtma topilmadi',
  orderNumber: (n: string) => `Buyurtma #${n}`,
  liveUpdates: 'Jonli yangilanishlar yoqilgan',
  total: 'Jami',
  noResults: 'Natija topilmadi',
  tryOtherSearch: "Boshqa so'z bilan qidiring",
  staffAccount: 'Xodim hisobi',
  staffSignOut: 'Xodim hisobidan chiqish',
  staffLoginTitle: 'Xodim va Super Admin',
  staffLoginHint: 'Ish email va parol bilan kiring.',
  staffFullLogin: "To'liq ekranli kirish",
  staffPanels: {
    SUPER_ADMIN: 'Super Admin paneli',
    MANAGER: 'Menejer paneli',
    RESTAURANT_OWNER: 'Restoran paneli',
    RESTAURANT_STAFF: 'Restoran paneli',
    COURIER: 'Kuryer paneli',
  } as Record<string, string>,
  orderStatus: {
    PENDING: 'Restoran kutmoqda',
    ACCEPTED: 'Buyurtma qabul qilindi',
    PREPARING: 'Taom tayyorlanmoqda',
    COURIER_ASSIGNED: 'Kuryer biriktirildi',
    PICKED_UP: 'Olib ketildi',
    DELIVERING: "Yo'lda",
    DELIVERED: 'Yetkazildi',
    CANCELLED: 'Bekor qilindi',
  } as Record<string, string>,
} as const;
